### ISSUE TITLE
Readme: toggling autosave fails

### ISSUE THREAD

**Issue by pataquets** [wlemuel/alarm-clock#10]
Doing as instructed in the readme gives:
`eval: Symbol’s function definition is void: alarm-clock-turn-autosave-on`

**Comment by wlemuel** [comment]
Hi,

Have you upgraded to the latest version? 
Please take a look at [related source code](https://github.com/wlemuel/alarm-clock/blob/master/alarm-clock.el#L304)

Thanks

**Comment by pataquets** [comment]
I (supposedly) was at the latest version when filing the issue, but turned out that another, older, package version was lying around in my Emacs dir (actually, Spacemacs managed packages).
In fact, double-checked for the relevant code, which puzzled me until I found the culprit.
Deleting the older package solved the issue.
Sorry for the noise.
