### ISSUE TITLE
Suggest shorter time message like m, h and s

### ISSUE THREAD

**Issue by eval-exec** [wlemuel/alarm-clock#11]
For example:
`1m` => `1 minute`
`1h` => `1 hour`
`2s` => `2 second`
`10h20m` => `10 hours and 20 minutes`

**Comment by wlemuel** [comment]
Thanks for the good suggestion, I have implemented this feature, but it has not been fully tested, if you want to have a try, you can refer to this [PR](https://github.com/wlemuel/alarm-clock/pull/12). And if it passes the test, I will merge this feature into the master branch

**Comment by wlemuel** [comment]
@eval-exec This feature has been merged into the master branch
Thank you for your suggestion.

**Comment by eval-exec** [comment]
Thank you, and thank you for your work :heart:
