### ISSUE TITLE
requirements does not list f.el

### ISSUE THREAD

**Issue by DavidBiesack** [wlemuel/alarm-clock#8]
Instructions are missing a prerequisite, package `f` :

```lisp
(package-install 'f)
```

**Comment by wlemuel** [comment]
The requirement of `f` package has been removed, you can pull the latest source codes from the `master` branch.

Thanks for your feadback.

**Comment by DavidBiesack** [comment]
Thanks @wlemuel !
I have forked this repo and added the ability to repeat the alarm _n_ times. See https://github.com/DavidBiesack/alarm-clock/blob/feature/repeating-alarm/README.md -- view the Enhancements. If you like those enhancements, I can clean up a bit and submit them as a PR to your original.
